kategorias:
  - animales
  - bevidas
  - diminutivos
  - direksion
  - elektriko
  - famiya
  - flores
  - frutas
  - gramer
  - insektos
  - kamareta-de-echar
  - kamaretas
  - kaza
  - kestiones
  - kolores
  - komidas
  - komputadora
  - kontenentes
  - kontinentes
  - kuzina
  - linguas
  - mamiferos
  - mobles
  - muzika
  - nasionalidad
  - natura
  - numeros
  - paises
  - plantas
  - polvos
  - profesion
  - puerpo
  - relijiones
  - ropa
  - saludos
  - servisio-de-meza
  - sivdades
  - sports
  - veikolos
  - zarzavates
orijenes:
  - Aki Yerushalayim
  - Balkanes
  - Estanbol
  - Gresia
  - Izmir
  - Jeneral
  - Ladinadores
  - Ladinokomunita
  - Otros
  - Salonik
  - Sarayevo
  - Torah-Tanah
  - NA
linguas:
  - arabo
  - bulgaro
  - ebreo
  - fransez
  - grego
  - italiano
  - portugez
  - turko
gramatika:
  - adjective
  - adverb
  - artikolo
  - noun
  - verb
  - preposition
  - pronoun
  - NA
gender:
  - feminine
  - masculine
  - both
  - NA
numero:
  - singular
  - plural
verbos-iregolares:
  - aver
  - azer
  - dar
  - dever
  - dizir
  - doler
  - entender
  - estar
  - fuyir
  - goler
  - inchir
  - introdusir
  - ir
  - kaver
  - kayer
  - kerer
  - konoser
  - kozer
  - kuzir
  - murir
  - oyir
  - poder
  - pueder
  - ser
  - salir
  - saver
  - servir
  - sintir
  - tener
  - trayer
  - ver
  - vinir
pajinas:
  abreviasiones.md:        abreviasiones.html
  artikels.md:             artikels.html
  biervos-de-la-gramer.md: gramer.html
  karakteres.md:           karakteres.html
  pejoratives.md:          pejoratives.html
  pronombres.md:           pronombres.html
  numeros.md:              numeros.html
  ser.md:                  ser.html
  estar.md:                estar.html
  sivdades.md:             sivdades.html
  nombres.md:              nombres.html
  presentasion.md:         presentasion.html
listas:
  sezones:
    - primavera
    - enverano
    - otonyo
    - invyerno
  mezes:
    - enero
    - fevrero
    - marso
    - avril
    - mayo
    - junio
    - djulio
    - agosto
    - septembre
    - oktobre
    - novembre
    - decembre
  dias-de-la-semana:
    - alhad
    - lunes
    - martes
    - mierkoles
    - djueves
    - viernes
    - shabat
  kontrarios:
    - grande
    - chiko
    - flako
    - godro
    - alto
    - basho
    - alegre
    - triste
    - vazio
    - yeno
    - mansevo
    - viejo
    - mansevo
    - aedado
    - largo
    - kurto
    - ermozo
    - feo
    - muevo
    - viejo
    - bueno
    - negro
    - prove
    - riko
    - suzio
    - limpio
    - frio
    - kayente
    - fasil
    - difisil
    - kolay
    - zor
    - duro
    - blando
    - liviano
    - pezgado
  enverano:
    - sol
    - plaj
    - banyo de sol
    - banyo de mar
    - parasol
    - shezlong
    - sudor
    - umidita
    - atabafarse de la kalor
    - antojos de sol
    - krema de sol
    - vakansas
    - kaza de kampanya
    - dondurma
    - yalada
    - piknik
    - fuego de shara
    - erkondishen
    - ayre kondisionado
    - pisina
    - havuz
  invierno:
    - luvia
    - pedrisko
    - inyeve
    - bruma
    - relampago
    - rayo
    - entezarse del frio
    - supa
    - chadir
    - guantes
  tiempos:
    - agora
    - amanyana
    - antiyer
    - anoche
    - anyo
    - ayer
    - dekada
    - dia
    - manyana
    - mediodia
    - medianoche
    - mez
    - midi
    - minuto
    - noche
    - ora
    - oy
    - punto
    - segundo
    - semana
    - siglo
    - tadre
    - tadres
  numeros:
    - zero
    - uno
    - dos
    - tres
    - kuatro
    - sinko
    - sesh
    - siete
    - ocho
    - mueve
    - diez
    - onse
    - dose
    - trese
    - katorse
    - kinse
    - vente
    - trenta
    - sien
    - mil
tiempos:
  - prezente
  - pasado
  - imperfekto
  - futuro
  - subjunktivo
  - subjunktivo imperfekto
  - kondisional
  - imperativo
  - djerundivo
  - partisipio pasado
pronombres:
  - yo
  - tu
  - el
  - mozotros
  - vozotros
  - eyos

